export const APP_NAME = "Web3 for all";

export const categories = [
  "all",
  "ethereum",
  "zk",
  "defi",
  "layer 1",
  "layer 2",
  "privacy",
];

export const images = [
  {
    name: "aave",
    id: "aave",
    category: ["all", "defi", "ethereum"],
    url: "https://ik.imagekit.io/onboard/web3forall/aave.png",
  },
  {
    name: "arweave",
    id: "arweave",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/arweave.png",
  },
  {
    name: "base",
    id: "base",
    category: ["all", "ethereum", "layer 2"],
    url: "https://ik.imagekit.io/onboard/web3forall/base.png",
  },
  {
    name: "berachain",
    id: "berachain",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/berachain.png",
  },
  {
    name: "chainlink",
    id: "chainlink",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/chainlink.png",
  },
  {
    name: "circle starks",
    id: "circle-starks",
    category: ["all", "zk", "privacy", "ethereum"],
    url: "https://ik.imagekit.io/onboard/web3forall/circle-starks.png",
  },
  {
    name: "eigenlayer",
    id: "eigenlayer",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/eigenlayer.png",
  },
  {
    name: "ens",
    id: "ens",
    category: ["all", "ethereum", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/ens.png",
  },
  {
    name: "ethereum wallet",
    id: "ethereum-wallet",
    category: ["all", "ethereum", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/ethereum-wallet.png",
  },
  {
    name: "ethereum",
    id: "ethereum",
    category: ["all", "ethereum", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/ethereum.png",
  },
  {
    name: "euler",
    id: "euler",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/euler.png",
  },
  {
    name: "farcaster",
    id: "farcaster",
    category: ["all", "ethereum"],
    url: "https://ik.imagekit.io/onboard/web3forall/farcaster.png",
  },
  {
    name: "layerzero",
    id: "layerzero",
    category: ["all"],
    url: "https://ik.imagekit.io/onboard/web3forall/layerzero.png",
  },
  {
    name: "livepeer",
    id: "livepeer",
    category: ["all", "ethereum"],
    url: "https://ik.imagekit.io/onboard/web3forall/livepeer.png",
  },
  {
    name: "monad",
    id: "monad",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/monad.png",
  },
  {
    name: "near",
    id: "near",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/near.png",
  },
  {
    name: "optimism",
    id: "optimism",
    category: ["all", "ethereum", "layer 2"],
    url: "https://ik.imagekit.io/onboard/web3forall/optimism.png",
  },
  {
    name: "scroll",
    id: "scroll",
    category: ["all", "zk", "layer 2"],
    url: "https://ik.imagekit.io/onboard/web3forall/scroll.png",
  },
  {
    name: "solana",
    id: "solana",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/solana.png",
  },
  {
    name: "uniswap",
    id: "uniswap",
    category: ["all", "ethereum", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/uniswap.png",
  },
  {
    name: "usdc",
    id: "usdc",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/usdc.png",
  },
  {
    name: "zksync",
    id: "zksync",
    category: ["all", "zk", "layer 2"],
    url: "https://ik.imagekit.io/onboard/web3forall/zksync.png",
  },
  {
    name: "zk proofs",
    id: "zk-proofs",
    category: ["all", "zk", "privacy"],
    url: "https://ik.imagekit.io/onboard/web3forall/zk-proofs.png",
  },
  {
    name: "flash loans",
    id: "flash-loans",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/flash-loans.png",
  },
  {
    name: "tornado cash",
    id: "tornado-cash",
    category: ["all", "privacy", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/tornado-cash.png",
  },
  {
    name: "defi",
    id: "defi",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/defi.png",
  },
    {
    name: "calimero",
    id: "calimero",
    category: ["all", "data privacy"],
    url: "https://raw.githubusercontent.com/calimero-network/calimero-network.github.io/master/static/eli5withtrademark.png",
  },
];
