export const APP_NAME = "Web3 for all";

export const categories = [
  "all",
  "ethereum",
  "zk",
  "defi",
  "layer 1",
  "layer 2",
  "privacy",
];

export const images = [
  {
    name: "aave",
    id: "aave",
    category: ["all", "defi", "ethereum"],
    url: "https://ik.imagekit.io/onboard/web3forall/aave.png",
  },

  {
    name: "base",
    id: "base",
    category: ["all", "ethereum", "layer 2"],
    url: "https://ik.imagekit.io/onboard/web3forall/base.png",
  },
  {
    name: "berachain",
    id: "berachain",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/berachain.png",
  },
  {
    name: "chainlink",
    id: "chainlink",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/chainlink.png",
  },
  {
    name: "circle starks",
    id: "circle-starks",
    category: ["all", "zk", "privacy", "ethereum"],
    url: "https://ik.imagekit.io/onboard/web3forall/circle-starks.png",
  },
  {
    name: "eigenlayer",
    id: "eigenlayer",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/eigenlayer.png",
  },
  {
    name: "ens",
    id: "ens",
    category: ["all", "ethereum", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/ens.png",
  },
  {
    name: "ethereum wallet",
    id: "ethereum-wallet",
    category: ["all", "ethereum", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/ethereum-wallet.png",
  },
  {
    name: "ethereum",
    id: "ethereum",
    category: ["all", "ethereum", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/ethereum.png",
  },
  {
    name: "euler",
    id: "euler",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/euler.png",
  },
  {
    name: "farcaster",
    id: "farcaster",
    category: ["all", "ethereum"],
    url: "https://ik.imagekit.io/onboard/web3forall/farcaster.png",
  },
  {
    name: "layerzero",
    id: "layerzero",
    category: ["all"],
    url: "https://ik.imagekit.io/onboard/web3forall/layerzero.png",
  },
  {
    name: "livepeer",
    id: "livepeer",
    category: ["all", "ethereum"],
    url: "https://ik.imagekit.io/onboard/web3forall/livepeer.png",
  },
  {
    name: "monad",
    id: "monad",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/monad.png",
  },
  {
    name: "near",
    id: "near",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/near.png",
  },
  {
    name: "nillion",
    id: "nillion",
    category: ["all", "privacy"],
    url: "https://ik.imagekit.io/onboard/web3forall/nillion.png",
    author: {
      name: "Helen",
      url: "https://github.com/hehozo",
      image: "https://github.com/hehozo.png",
    },
  },
  {
    name: "optimism",
    id: "optimism",
    category: ["all", "ethereum", "layer 2"],
    url: "https://ik.imagekit.io/onboard/web3forall/optimism.png",
  },
  {
    name: "scroll",
    id: "scroll",
    category: ["all", "zk", "layer 2"],
    url: "https://ik.imagekit.io/onboard/web3forall/scroll.png",
  },
  {
    name: "solana",
    id: "solana",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/solana.png",
  },
  {
    name: "uniswap",
    id: "uniswap",
    category: ["all", "ethereum", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/uniswap.png",
  },
  {
    name: "usdc",
    id: "usdc",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/usdc.png",
  },
  {
    name: "zksync",
    id: "zksync",
    category: ["all", "zk", "layer 2"],
    url: "https://ik.imagekit.io/onboard/web3forall/zksync.png",
  },
  {
    name: "zk proofs",
    id: "zk-proofs",
    category: ["all", "zk", "privacy"],
    url: "https://ik.imagekit.io/onboard/web3forall/zk-proofs.png",
  },
  {
    name: "flash loans",
    id: "flash-loans",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/flash-loans.png",
  },
  {
    name: "tornado cash",
    id: "tornado-cash",
    category: ["all", "privacy", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/tornado-cash.png",
  },
  {
    name: "defi",
    id: "defi",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/onboard/web3forall/defi.png",
  },
  {
    name: "calimero",
    id: "calimero",
    category: ["all", "data privacy"],
    url: "https://ik.imagekit.io/onboard/web3forall/calimero.png",
  },
  {
    name: "arweave",
    id: "arweave",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/onboard/web3forall/arweave.png",
    author: {
      name: "Helen",
      url: "https://github.com/hehozo",
      image: "https://github.com/hehozo.png",
    },
  },
  {
    name: "seed phrase, private key, and public key",
    id: "seed-phrase-private-key-and-public-key",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/rekahbeee/seed-phrase-private-key-and-public-key.svg",
    author: {
      name: "Rebekah",
      url: "https://github.com/rekahbeee",
      image: "https://github.com/rekahbeee.png",
    },
  },
  {
    name: "bridging",
    id: "bridging",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/rekahbeee/Bridging.svg?updatedAt=1729932421496",
    author: {
      name: "Rebekah",
      url: "https://github.com/rekahbeee",
      image: "https://github.com/rekahbeee.png",
    },
  },
  {
    name: "liquid-staking",
    id: "liquid-staking",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/rekahbeee/liquid-staking.svg?updatedAt=1731847131334",
    author: {
      name: "Rebekah",
      url: "https://github.com/rekahbeee",
      image: "https://github.com/rekahbeee.png",
    },
  },
  {
    name: "optimistic-rollups",
    id: "optimistic-rollups",
    category: ["all", "ethereum", "layer 2"],
    url: "https://ik.imagekit.io/rekahbeee/optimistic-rollups.svg?updatedAt=1734688820473",
    author: {
      name: "Rebekah",
      url: "https://github.com/rekahbeee",
      image: "https://github.com/rekahbeee.png",
    },
  },
  {
    name: "zk-rollups",
    id: "zk-rollups",
    category: ["all", "ethereum", "layer 2", "zk"],
    url: "https://ik.imagekit.io/rekahbeee/zk-rollups.svg?updatedAt=1747853441835",
    author: {
      name: "Rebekah",
      url: "https://github.com/rekahbeee",
      image: "https://github.com/rekahbeee.png",
    },
  },
  {
    name: "Suilend",
    id: "suilend",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/tcldcgu1o/Suilend%20.jpeg?updatedAt=1729447753143",
    author: {
      name: "Goodylili",
      url: "https://github.com/goodylili",
      image: "https://github.com/goodylili.png",
    },
  },
  {
    name: "Cosmos",
    id: "cosmos",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/tcldcgu1o/Cosmos.jpeg?updatedAt=1729448927962",
    author: {
      name: "Goodylili",
      url: "https://github.com/goodylili",
      image: "https://github.com/goodylili.png",
    },
  },
  {
    name: "Osmosis",
    id: "osmosis",
    category: ["all", "DeFi", "layer 1"],
    url: "https://ik.imagekit.io/tcldcgu1o/Osmosis.jpeg?updatedAt=1729435019335",
    author: {
      name: "Goodylili",
      url: "https://github.com/goodylili",
      image: "https://github.com/goodylili.png",
    },
  },
  {
    name: "Sui",
    id: "sui",
    category: ["all", "layer 1"],
    url: "https://ik.imagekit.io/tcldcgu1o/Sui.jpeg?updatedAt=1729448896995",
    author: {
      name: "Goodylili",
      url: "https://github.com/goodylili",
      image: "https://github.com/goodylili.png",
    },
  },
  {
    name: "Axelar",
    id: "axelar",
    category: ["all", "layer 1", "ethereum"],
    url: "https://ik.imagekit.io/tcldcgu1o/Axelar.jpeg?updatedAt=1729435019808",
    author: {
      name: "Goodylili",
      url: "https://github.com/goodylili",
      image: "https://github.com/goodylili.png",
    },
  },
  {
    name: "TradePort",
    id: "tradeport",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/tcldcgu1o/TradePort.jpeg?updatedAt=1729435018464",
    author: {
      name: "Goodylili",
      url: "https://github.com/goodylili",
      image: "https://github.com/goodylili.png",
    },
  },
  {
    name: "Jumper",
    id: "jumper",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/tcldcgu1o/Jumper.jpeg?updatedAt=1729449044500",
    author: {
      name: "Goodylili",
      url: "https://github.com/goodylili",
      image: "https://github.com/goodylili.png",
    },
  },
  {
    name: "PStake",
    id: "pstake",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/tcldcgu1o/PStake.jpeg?updatedAt=1729449065394",
    author: {
      name: "Goodylili",
      url: "https://github.com/goodylili",
      image: "https://github.com/goodylili.png",
    },
  },
  {
    name: "SpringSui",
    id: "springsui",
    category: ["all", "defi"],
    url: "https://ik.imagekit.io/tcldcgu1o/SpringSui.jpeg?updatedAt=1729448992415",
    author: {
      name: "Goodylili",
      url: "https://github.com/goodylili",
      image: "https://github.com/goodylili.png",
    },
  },
  {
    name: "Wormhole",
    id: "wormhole",
    category: ["all"],
    url: "https://raw.githubusercontent.com/ilariae/web3forall/main/Wormhole-Excalidraw.png",
    author: {
      name: "Wormhole",
      url: "https://github.com/wormhole-foundation",
      image: "https://github.com/wormhole-foundation.png",
    },
  },
];